server:
  port: 8092

spring:
  application:
    name: msvc-logistic

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/logistic_db
    username: tefa
    password: 0203

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  

eureka:
  instance:
    hostname: localhost
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/

