package com.microservice.rrhh.model;

public enum EmployeePosition {
	GERENTE_GENERAL,
    COORDINADOR_RECURSOS_HUMANOS,
    JEFE_DE_TI,
    SUPERVISOR_DE_FINANZAS,
    ANALISTA_DE_DATOS,
    ASISTENTE_ADMINISTRATIVO,
    CONTADOR,
    RESPONSABLE_DE_MARKETING,
    ENCARGADO_DE_COMPRAS,
    JEFE_DE_VENTAS,

    RECLUTADOR,
    ESPECIALISTA_EN_CAPACITACION,
    ENCARGADO_DE_NOMINA,
    ENCARGADO_DE_BENEFICIOS,
    ASESOR_DE_BIENESTAR,

    DESARROLLADOR_BACKEND,
    DESARROLLADOR_FRONTEND,
    ADMINISTRADOR_DE_REDES,
    SOPORTE_TECNICO,
    INGENIERO_DE_SEGURIDAD_INFORMATICA,
    ANALISTA_DE_SISTEMAS,

    ANALISTA_FINANCIERO,
    CONTABLE,
    TESORERIA,
    AUDITOR_INTERNO,
    ANALISTA_DE_RIESGOS,

    EJECUTIVO_DE_VENTAS,
    SUPERVISOR_DE_VENTAS,
    GESTOR_DE_CUENTAS,
    ESPECIALISTA_EN_ATENCION_AL_CLIENTE,
    COORDINADOR_DE_VENTAS,
    VENDEDOR,

    ESPECIALISTA_EN_SEO,
    COMMUNITY_MANAGER,
    ANALISTA_DE_MARKETING_DIGITAL,
    DIRECTOR_DE_MARCA,
    COORDINADOR_DE_PUBLICIDAD,

    SUPERVISOR_DE_PRODUCCION,
    JEFE_DE_LOGISTICA,
    ANALISTA_DE_PROYECTOS,
    COORDINADOR_DE_SUMINISTROS,
    GESTOR_DE_INVENTARIOS
}
