package com.microservice.rrhh.model;

public enum PermissionType {
	PERMISO_ENFERMEDAD,
    PERMISO_PERSONAL,
    PERMISO_LICENCIA,
    PERMISO_EXAMEN,
    PERMISO_VIAJE,
    PERMISO_FAMILIAR,
    PERMISO_COMPENSATORIO,
    PERMISO_JUDICIAL,
    PERMISO_CELEBRACION,
    PERMISO_OTRO 
}
