package com.microservice.rrhh.model;

public enum RoleType {
	ADMINISTRADOR_GENERAL,
	ADMINISTRADOR_RRHH,
	ADMINISTRADOR_LOGISTICA,
	ADMINISTRADOR_VENTAS,
	ADMINISTRADOR_PLANEACION,
	ADMINISTRADOR_CRM,
	COORDINADOR_CRM,
	ASESOR_CRM
}
