server:
  port: 8094

spring:
  application:
    name: msvc-plannig
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.109:5432/planning_db
    
    username: tefa
    password: "0203"

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
eureka:
  instance:
    hostname: localhost
  client:
   service-url:
    defaultZone: http://msvc-eureka:8761/eureka/ 
