server:
  port: 8094

spring:
  application:
    name: msvc-plannig

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://umqnxdy2mw5i5ig2jhsf:TimFjoAlhmlatYFbTYPWBDGsk44BmK@botxiqb5gqg0ihfadqnj-postgresql.services.clever-cloud.com:50013/botxiqb5gqg0ihfadqnj
    username: umqnxdy2mw5i5ig2jhsf
    password: TimFjoAlhmlatYFbTYPWBDGsk44BmK

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
