server:
  port: 8096

spring:
  application:
    name: msvc-auth

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: Yamada

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
   init:
      mode: always 
      platform: postgresql
  
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/	

jwt:
  secret: "c2VjcmV0LXNlY3JldC1zZWNyZXQtc2VjcmV0LXNlY3JldA=="
  access-token:
    expiration: 100000   
  refresh-token:
    expiration: 604800000
