    
server:
  port: 8095

spring:
  application:
    name: msvc-rrhh
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rrhh_db
    username: postgres

    password: Yamada


  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  servlet:
    multipart:
      max-file-size: 70MB
      max-request-size: 70MB


eureka:
  instance:
    hostname: localhost
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
