server:
  port: 8081

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
  main:
    web-application-type: reactive   
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-auth
          uri: http://msvc-auth:8096
          predicates:
            - Path=/api/auth/**

        - id: msvc-crm
          uri: http://msvc-crm:8090
          predicates:
            - Path=/api/v1/crm/**

        - id: msvc-sales
          uri: http://msvc-sales:8091
          predicates:
            - Path=/api/v1/sales/**

        - id: msvc-logistic
          uri: http://msvc-logistic:8092
          predicates:
            - Path=/api/v1/logistic/**

        - id: msvc-manufacture
          uri: http://msvc-manufacture:8093
          predicates:
            - Path=/api/v1/manufacture/**

        - id: msvc-planning
          uri: http://msvc-planning:8094
          predicates:
            - Path=/api/v1/planning/**

        - id: msvc-rrhh
          uri: http://msvc-rrhh:8095
          predicates:
            - Path=/api/v1/rrhh/**

eureka:
  client:
    register-with-eureka: false